import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";

const TUONGNGUYEN_PROXY_ROOT = "https://proxy.tuongnguyen.work";

export function registerTuongNguyenProxy(pi: ExtensionAPI): void {
  pi.registerProvider("tuongnguyen-proxy", {
    name: "Tuong Nguyen Proxy",
    authHeader: true,
    models: [
      {
        id: "glm-5.2",
        name: "GLM 5.2",
        api: "anthropic-messages",
        baseUrl: TUONGNGUYEN_PROXY_ROOT,
        reasoning: true,
        input: ["text"],
        cost: { input: 1.4, output: 4.4, cacheRead: 0.26, cacheWrite: 0 },
        contextWindow: 1000000,
        maxTokens: 131072,
        thinkingLevelMap: {
          minimal: null,
          low: "high",
          medium: "high",
          high: "high",
          max: "max",
        },
        compat: { forceAdaptiveThinking: true },
      },
      {
        id: "gpt-5.6-sol",
        name: "GPT-5.6 Sol",
        api: "openai-completions",
        baseUrl: `${TUONGNGUYEN_PROXY_ROOT}/v1`,
        reasoning: true,
        input: ["text", "image"],
        cost: { input: 5, output: 30, cacheRead: 0.5, cacheWrite: 6.25 },
        contextWindow: 500000,
        maxTokens: 128000,
        thinkingLevelMap: {
          off: "none",
          minimal: null,
          low: "low",
          medium: "medium",
          high: "high",
          xhigh: "xhigh",
          max: "max",
        },
        compat: {
          supportsDeveloperRole: false,
          supportsReasoningEffort: true,
          maxTokensField: "max_tokens",
        },
      },
      {
        id: "gpt-5.6-terra",
        name: "GPT-5.6 Terra",
        api: "openai-completions",
        baseUrl: `${TUONGNGUYEN_PROXY_ROOT}/v1`,
        reasoning: true,
        input: ["text", "image"],
        cost: { input: 2.5, output: 15, cacheRead: 0.25, cacheWrite: 3.125 },
        contextWindow: 500000,
        maxTokens: 128000,
        thinkingLevelMap: {
          off: "none",
          minimal: null,
          low: "low",
          medium: "medium",
          high: "high",
          xhigh: "xhigh",
          max: "max",
        },
        compat: {
          supportsDeveloperRole: false,
          supportsReasoningEffort: true,
          maxTokensField: "max_tokens",
        },
      },
      {
        id: "gpt-5.6-luna",
        name: "GPT-5.6 Luna",
        api: "openai-completions",
        baseUrl: `${TUONGNGUYEN_PROXY_ROOT}/v1`,
        reasoning: true,
        input: ["text", "image"],
        cost: { input: 5, output: 30, cacheRead: 0.5, cacheWrite: 6.25 },
        contextWindow: 1050000,
        maxTokens: 128000,
        thinkingLevelMap: {
          off: "none",
          minimal: null,
          xhigh: "xhigh",
          max: "max",
        },
        compat: {
          supportsDeveloperRole: false,
          supportsReasoningEffort: true,
          maxTokensField: "max_tokens",
        },
      },
      {
        id: "gpt-image-2",
        name: "GPT Image 2",
        api: "openai-completions",
        baseUrl: `${TUONGNGUYEN_PROXY_ROOT}/v1`,
        reasoning: false,
        input: ["image"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 1000000,
        maxTokens: 128000,
        compat: {
          supportsDeveloperRole: false,
          supportsReasoningEffort: true,
          maxTokensField: "max_tokens",
        },
      },
      {
        id: "gemini-3.7-flash",
        name: "Gemini 3.7 Flash",
        api: "google-generative-ai",
        baseUrl: `${TUONGNGUYEN_PROXY_ROOT}/v1beta`,
        reasoning: true,
        input: ["text", "image"],
        cost: { input: 1.5, output: 7.5, cacheRead: 0.15, cacheWrite: 0 },
        contextWindow: 1048576,
        maxTokens: 65536,
        thinkingLevelMap: { off: null },
      },
      {
        id: "deepseek-v4-pro",
        name: "DeepSeek V4 Pro",
        api: "openai-completions",
        baseUrl: `${TUONGNGUYEN_PROXY_ROOT}/v1`,
        reasoning: true,
        input: ["text"],
        cost: { input: 0.435, output: 0.87, cacheRead: 0.004, cacheWrite: 0 },
        contextWindow: 1000000,
        maxTokens: 384000,
        thinkingLevelMap: {
          off: null,
          minimal: null,
          low: null,
          medium: null,
          high: "high",
          xhigh: null,
          max: "max",
        },
        compat: {
          supportsDeveloperRole: false,
          supportsReasoningEffort: true,
          maxTokensField: "max_tokens",
        },
      },
    ],
  });
}
