import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { NativeImageCapture } from "../../shared/NativeImageCapture";
import { IMAGE_INPUT_LIMITS } from "./image-limits";

const TUONGNGUYEN_PROXY_ROOT = "https://proxy.tuongnguyen.work";

export function registerTuongNguyenProxy(pi: ExtensionAPI): void {
  pi.registerProvider("tuongnguyen-proxy", {
    name: "Tuong Nguyen Proxy",
    authHeader: true,
    // Routes this provider's openai-completions models through the image tee
    // (per-model `api` still wins, so Gemini/Anthropic entries are untouched).
    api: "openai-completions",
    streamSimple: NativeImageCapture.streamSimpleFor("tuongnguyen-proxy"),
    models: [
      {
        id: "swe-2",
        name: "SWE 2",
        api: "openai-completions",
        baseUrl: `${TUONGNGUYEN_PROXY_ROOT}/v1`,
        reasoning: true,
        input: ["text"],
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 262144,
        maxTokens: 32768,
        thinkingLevelMap: {
          off: null,
          minimal: null,
          low: null,
          medium: "medium",
          high: "high",
          xhigh: null,
          max: "max",
        },
        compat: {
          supportsDeveloperRole: false,
          supportsReasoningEffort: true,
          maxTokensField: "max_tokens",
        },
      },
      {
        id: "gpt-6-sol",
        name: "GPT-6 Sol",
        api: "openai-completions",
        baseUrl: `${TUONGNGUYEN_PROXY_ROOT}/v1`,
        reasoning: true,
        input: ["text", "image"],
        inputLimits: IMAGE_INPUT_LIMITS,
        cost: { input: 5, output: 30, cacheRead: 0.5, cacheWrite: 6.25 },
        contextWindow: 500000,
        maxTokens: 128000,
        thinkingLevelMap: {
          off: "none",
          minimal: null,
          low: "low",
          medium: "medium",
          high: "high",
          xhigh: "xhigh",
          max: "max",
        },
        compat: {
          supportsDeveloperRole: false,
          supportsReasoningEffort: true,
          maxTokensField: "max_tokens",
        },
      },
      {
        id: "gpt-6-luna",
        name: "GPT-6 Luna",
        api: "openai-completions",
        baseUrl: `${TUONGNGUYEN_PROXY_ROOT}/v1`,
        reasoning: true,
        input: ["text", "image"],
        inputLimits: IMAGE_INPUT_LIMITS,
        cost: { input: 5, output: 30, cacheRead: 0.5, cacheWrite: 6.25 },
        contextWindow: 1050000,
        maxTokens: 128000,
        thinkingLevelMap: {
          off: "none",
          minimal: null,
          xhigh: "xhigh",
          max: "max",
        },
        compat: {
          supportsDeveloperRole: false,
          supportsReasoningEffort: true,
          maxTokensField: "max_tokens",
        },
      },
      {
        id: "gemini-3.8-flash",
        name: "Gemini 3.8 Flash",
        api: "google-generative-ai",
        baseUrl: `${TUONGNGUYEN_PROXY_ROOT}/v1beta`,
        reasoning: true,
        input: ["text", "image"],
        inputLimits: IMAGE_INPUT_LIMITS,
        cost: { input: 1.5, output: 7.5, cacheRead: 0.15, cacheWrite: 0 },
        contextWindow: 1048576,
        maxTokens: 65536,
        thinkingLevelMap: { off: null, minimal: null },
      },
      {
        id: "claude-opus-4-6",
        name: "Claude Opus 4.6 (Thinking)",
        api: "anthropic-messages",
        baseUrl: TUONGNGUYEN_PROXY_ROOT,
        reasoning: true,
        input: ["text", "image"],
        inputLimits: IMAGE_INPUT_LIMITS,
        cost: { input: 15, output: 75, cacheRead: 1.5, cacheWrite: 18.75 },
        contextWindow: 200000,
        maxTokens: 128000,
        thinkingLevelMap: {
          minimal: null,
          low: "low",
          medium: "medium",
          high: "high",
          xhigh: "xhigh",
          max: "max",
        },
        compat: { forceAdaptiveThinking: true },
      },
      {
        id: "claude-sonnet-4-6",
        name: "Claude Sonnet 4.6 (Thinking)",
        api: "anthropic-messages",
        baseUrl: TUONGNGUYEN_PROXY_ROOT,
        reasoning: true,
        input: ["text", "image"],
        inputLimits: IMAGE_INPUT_LIMITS,
        cost: { input: 3, output: 15, cacheRead: 0.3, cacheWrite: 3.75 },
        contextWindow: 200000,
        maxTokens: 128000,
        thinkingLevelMap: {
          minimal: null,
          low: "low",
          medium: "medium",
          high: "high",
          xhigh: "xhigh",
          max: "max",
        },
        compat: { forceAdaptiveThinking: true },
      },
      {
        id: "deepseek-v4.1-flash",
        name: "DeepSeek V4.1 Flash",
        api: "openai-completions",
        baseUrl: `${TUONGNGUYEN_PROXY_ROOT}/v1`,
        reasoning: true,
        input: ["text"],
        cost: { input: 0.435, output: 0.87, cacheRead: 0.004, cacheWrite: 0 },
        contextWindow: 1000000,
        maxTokens: 384000,
        thinkingLevelMap: {
          off: null,
          minimal: null,
          low: null,
          medium: null,
          high: "high",
          xhigh: null,
          max: "max",
        },
        compat: {
          supportsDeveloperRole: false,
          supportsReasoningEffort: true,
          maxTokensField: "max_tokens",
        },
      },
    ],
  });
}
